mySite/authentication/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^profile_edit/$', views.profile_edit, name='profile_edit'),
    url(r'^checkemail/$', views.checkemail, name='checkemail'),
    url(r'^password/$', views.password, name='password'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

mySite/master/urls.py
# master/urls.py
"""master URL Configuration"""
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.master_home, name='master_home'),
]

mySite/mistake/urls.py
# master/urls.py
"""master URL Configuration"""
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add_report/$', views.add_report, name='add_report'),
]

mySite/records/urls.py
# records/urls.py
"""records URL Configuration"""
from django.conf.urls import url
from . import views, views_reg, views_news

urlpatterns = [
    url(r'^$', views.person_list, name='person_list'),
    url(r'^ajax_person_list/', views.ajax_person_list, name='ajax_person_list'),
    url(r'^table/$', views.person_table, name='person_table'),
    url(r'^persondetail/(?P<person_id>\d+)/$', views.person_detail, name='person_detail'),
    url(r'^personrelationship/(?P<person_id>\d+)/$', views.person_relationship, name='person_relationship'),
    url(r'^event_list/$', views.event_list, name='event_list'),
    url(r'^personfamily/(?P<person_id>\d+)/$', views.person_family, name='person_family'),
    url(r'^event_detail/(?P<event_id>\d+)/$', views.event_detail, name='event_detail'),

    url(r'^check_person/$', views_reg.check_person, name='check_person'),
    url(r'^add_person/$', views_reg.add_person, name='add_person'),
    url(r'^edit_person/(?P<person_id>\d+)/$', views_reg.edit_person, name='edit_person'),

    url(r'^check_event/(?P<person_id>\d+)/$', views_reg.check_event, name='check_event'),
    url(r'^add_event/(?P<person_id>\d+)/$', views_reg.add_event, name='add_event'),
    url(r'^person_event_matching/(?P<person_id>\d+)/$', views_reg.person_event_matching, name='person_event_matching'),

    url(r'^check_evidence/(?P<personevent_id>\d+)/$', views_reg.check_evidence, name='check_evidence'),
    url(r'^add_evidence/$', views_reg.add_evidence, name='add_evidence'),
# 9월 21일 추가함
    url(r'^evidence_add_person/(?P<news_id>\d+)/(?P<event_id>\d+)/$', views_reg.evidence_add_person, name='evidence_add_person'),

# 10/28 
    url(r'^add_event_news/(?P<event_id>\d+)/$', views_news.add_event_news, name='add_event_news'),

    url(r'^ajax_person_like/(?P<person_id>\d+)/$', views.ajax_person_like, name='ajax_person_like'),
    url(r'^ajax_person_following/(?P<person_id>\d+)/$', views.ajax_person_following, name='ajax_person_following'),

    url(r'^ajax_event_like/(?P<event_id>\d+)/$', views.ajax_event_like, name='ajax_event_like'),
    url(r'^ajax_event_following/(?P<event_id>\d+)/$', views.ajax_event_following, name='ajax_event_following'),

    url(r'^tag/(?P<tag_name>\w+)/(?P<type>\w+)/$', views.tag, name='tag'),
    url(r'^top_search/$', views.top_search, name='top_search'),

    url(r'^register_relation/(?P<person_id>\d+)/$', views.register_relation, name='register_relation'),
    url(r'^search_persons/$', views.search_persons, name='search_persons'),

    url(r'^aboutUS/$', views.aboutUS, name='aboutUS'),

]

mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as login_views
from django.conf.urls.static import static
from django.shortcuts import redirect

from mySite.authentication import views as signup_views

urlpatterns = [
    url('^$', lambda r: redirect('/records/'), name='home'),
    url(r'^xmlyoon/', admin.site.urls),
    url(r'^master/', include('mySite.master.urls', namespace='master')),
    url(r'^records/', include('mySite.records.urls', namespace='records')),
    url(r'^authentication/', include('mySite.authentication.urls', namespace='authentication')),
    url(r'^mistake/', include('mySite.mistake.urls', namespace='mistake')),
    url(r'^comments/', include('mySite.comments.urls', namespace='comments')),
    url(r'^activity/', include('mySite.activity.urls', namespace='activity')),
    url(r'^nickname/', include('mySite.nickname.urls', namespace='nickname')),
    url(r'^calendars/', include('mySite.calendars.urls', namespace='calendars')),

    url(r'^accounts/', include('allauth.urls')),
    # url(r'^evidence/', include('evidence.urls', namespace='evidence')),

    url(r'^signup/$', signup_views.signup, name='signup'),
    url(r'^login', login_views.login, {'template_name': 'authentication/login.html'},
        name='login'),
    url(r'^logout', signup_views.logout, name='logout'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mySite/comments/forms.py
from django import forms

from .models import Comment, ENComment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['evidence', 'parent', 'content']

class ENCommentForm(forms.ModelForm):

    class Meta:
        model = ENComment
        fields = ['event', 'news', 'parent', 'content']

mySite/master/forms.py
# master/forms.py
#
# class ArticleForm(forms.ModelForm):
#	title = forms.CharField(
#		widgets = forms.TextInput(attrs={'class':'form-control'}), max_length=255)
#	title = forms.CharField(
#		widgets = forms.HiddenInput()
# 	title = forms.CharField(
#		widgets = forms.Textarea(attrs={'class':'form-control'}), max_length=4000)
# 	title = forms.CharField(
#		widgets = forms.TextInput(attrs={'class':'form-control'}), max_length=4000, required=False, help_text='.....')
#
#

from django import forms

# Create your forms here.

mySite/mistake/forms.py
from django import forms

from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['name', 'url', 'content', 'picture', 'email']

mySite/activity/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Notification

@login_required
def notifications(request):
    notifications = Notification.objects.filter(to_user=request.user)
    unread = Notification.objects.filter(to_user=request.user, is_read=False)

    for notification in unread:
        notification.is_read = True
        notification.save()

    return render(request, 'activity/notifications.html', {
            'notifications': notifications,
        })

@login_required
def last_notifications(request):
    user = request.user
    notifications = Notification.objects.filter(to_user=user)[:8]

    for notification in notifications:
        notification.is_read = True 
        notification.save()

    return render(request, 'activity/partial/last_notifications.html', {
            'notifications': notifications,
        })

@login_required
def check_notifications(request):
    user = request.user
    notifications = Notification.objects.filter(to_user=user,
                                                is_read=False).count()
    return HttpResponse(notifications)

mySite/authentication/views.py
import os
from django.conf import settings
from django.contrib import auth

from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.models import User
from django.core.checks import messages
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.db.models import Count
from PIL import Image

from mySite.records.models import Person, Tag
from .models import Profile
from .forms import SignUpForm, ProfileForm, ChangePasswordForm
from .tokens import account_activation_token

def signup(request):
    
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            # email = form.cleaned_data.get('email')
            # username = form.cleaned_data.get('username')
            # first_name = form.cleaned_data.get('first_name')
            # password = form.cleaned_data.get('password')
            # User.objects.create_user(username=username, first_name=first_name, 
            #                 password=password, email=email)

            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            message = render_to_string('authentication/active_email.html', {
                    'user':user, 'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })

            mail_subject = 'Activate your account of "IRememberYourPast.com".'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return render(request, 'authentication/send_email_for_confirmation.html', {'email': to_email })

        else:
            return render(request, 'authentication/signup.html', {'form': form })

    else:
        form = SignUpForm()
        return render(request, 'authentication/signup.html', {'form': form })

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # Profile.objects.create(user=request.user)

        return redirect('authentication:profile_edit')
    else:
        return 

@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            # profile = form.save(commit=False)
            # profile.user = request.user
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            width = form.cleaned_data.get('width')
            height = form.cleaned_data.get('height')
            picture = form.cleaned_data.get('picture')

            image = Image.open(picture)
            cropped_image = image.crop((x, y, width+x, height+y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            savefile = '/user_profile/' + request.user.username + '-' + picture.name
            filename = settings.MEDIA_ROOT + savefile
            resized_image.save( filename )

            if Profile.objects.filter(user=request.user).count():
                Profile.objects.filter(user=request.user).update(picture=savefile)
            else:
                Profile.objects.create(user=request.user, picture=savefile)
            return redirect('authentication:profile_edit')
    else:
        user = request.user
        form = ProfileForm()

        person_list = Person.objects.annotate(
            num_following=Count('following')).filter(status='P', 
            created_user=user).order_by('-num_following')

        popular_tags = Tag.get_person_popular_tags()
        following = Person.get_persons_following()[:10]
        context = {'person_list': person_list, 'popular_tags': popular_tags, 
                    'following': following, 'form':form}
    return render(request, 'authentication/person_profile.html', context)


def logout(request):
    auth.logout(request)

    return redirect('login')


############################
# Email Check
############################
def checkemail(request):
    data = {}
    email = request.GET.get('email')
    if email:
        email = User.objects.filter(email = email).exists()
        if email:
            data["exists"] = True
        
    return JsonResponse(data, safe=False)

############################
# Change Password
############################
@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('authentication:profile_edit')

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'authentication/password.html', {'form': form})

mySite/calendars/views.py
from datetime import date, timedelta
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from mySite.records.models import Event

# Create your views here.
@login_required
def event_list(request):
    today = date.today()
    year = today.year
    from_dt = today + timedelta(days=-90)
    to_dt = today + timedelta(days=90)

    event_list = {}
    events = Event.objects.filter(happened_at__isnull=False)
    times = [ time for time in range(10, 23)]
    # print(times)
    for event in events:
        event_list[event.id] = {}
        event_list[event.id]['id'] = event.id
        event_list[event.id]['name'] = event.name
        hdate = event.happened_at.replace(year=year)
        # print(hdate)
        event_list[event.id]['hdate'] = hdate

    print(event_list)

    return render(request, 'calendars/event_list.html', {
            'event_list':event_list,
            'times':times,
        })

mySite/comments/views.py
from django.shortcuts import render

# from decorators import ajax_required
from .models import Comment, ENComment
from .forms import CommentForm, ENCommentForm
# Create your views here.

def evidence_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        evidence = request.POST.get('evidence')

        if form.is_valid():
            user = request.user
            comment = form.save(commit=False)
            comment.created_user = user
            comment.save()

        comment_list = Comment.objects.filter(evidence__id = evidence, parent__isnull=True)
        return render(request, 'comments/partial/comment.html',
            { 'comment_list': comment_list, 'evidence_id': evidence })

    else:
        evidence = request.GET.get('evidence_id')
        comment_list = Comment.objects.filter(evidence__id = evidence, parent__isnull=True)
        return render(request, 'comments/partial/comment.html',
            { 'comment_list': comment_list, 'evidence_id': evidence })

def evi_comment_delete(request):
    comment_id = request.GET.get('comment')
    evidence = request.GET.get('evidence')

    Comment.objects.get(id=comment_id).delete()

    comment_list = Comment.objects.filter(evidence__id = evidence, parent__isnull=True)
    return render(request, 'comments/partial/comment.html',
        { 'comment_list': comment_list, 'evidence_id': evidence })

    

def en_comment(request):
    if request.method == 'POST':
        form = ENCommentForm(request.POST)
        eventid = request.POST.get('event')
        newsid = request.POST.get('news')

        if form.is_valid():
            user = request.user
            comment = form.save(commit=False)
            comment.created_user = user
            comment.save()

        comment_list = ENComment.objects.filter(
                event__id = eventid, news__id = newsid, parent__isnull=True)
        return render(request, 'comments/partial/en_comment.html',
            { 'comment_list': comment_list, 'evidence_id': eventid })

    else:
        newsid = request.GET.get('news')
        eventid = request.GET.get('event')
        comment_list = ENComment.objects.filter(
                event__id = eventid, news__id = newsid, parent__isnull=True)
        return render(request, 'comments/partial/en_comment.html',
            { 'comment_list': comment_list, 'event_id': eventid, 'news_id': newsid })


def en_comment_delete(request):
    comment_id = request.GET.get('comment')
    event = request.GET.get('event')
    newsid = request.GET.get('news')

    ENComment.objects.get(id=comment_id).delete()

    comment_list = ENComment.objects.filter(
        event__id = event, news__id = newsid, parent__isnull=True)
    return render(request, 'comments/partial/en_comment.html',
        { 'comment_list': comment_list, 'event_id': event, 'news_id': newsid })

mySite/master/views.py
# master/views.py
from django.shortcuts import render

# Create your views here.
def master_home(request):
    return render(request, 'base.html')

mySite/mistake/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ReportForm

# Create your views here.
def add_report(request):

    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, "오류가 보고 되었습니다.")
            return redirect('home')

    else:
        if request.user:
            email = request.user.username
        form = ReportForm(initial={'email':email})

    return render(request, 'mistake/add_report.html', {'form':form})

mySite/templates/aboutUS.html
{% extends 'base.html' %}
{% load static %}

{% block header-index %}
    {% include 'title.html' %}
    <a href="{% url 'records:check_person' %}"> 
            <button type='button' class='btn btn-primary pull-right'>사람/시건/뉴스 등록</button>
    </a>
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home' %}"> <i class="fa fa-home"></i> Home </a> 
        </li>
        <li>
            about US 
        </li>
        
    </ol>
{% endblock header-index %}


{% block content %}
    <div class="wrapper wrapper-content">
        <div class="row animated fadeInRight">
        {# Check Person #}

            <div class='col-md-12'>
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5> 왜 사이트를 만들었나요? </h5>
                    </div>
                    <div class="ibox-content">
                      <ul style="padding: 10px">  
                        <li> 역사를 기억하지 못하는 자, 다시 그 역사를 반복할 것이다. </li>
                        <li> 역사를 잊은 민족에게 미래는 없다. </li>
                        <li> 자랑스러운 기억도 부끄러운 기억도 기억할 때 의미가 있습니다. </li>
                        <li> 외환 위기 때 금모이기 운동에 참여했던, 태안 앞바다 검은 기름을 걷어내기 위한 봉사 활동을 자랑스럽게 생각하고, 후손들에게 당당하게 이야기를 해야 합니다. </li>
                        <li> 조국의 독립을 위해 이국 땅에서 쓸쓸히 죽어간 이들을 기억해야 합니다. </li>
                        <li> 정의를 위해 내부의 비리를 고발한 사람을 기억하고 보호해야 합니다. </li>
                        <li> 나라를 팔아먹은 이들을 기억하고 반면 교사로 삼아야 합니다. </li>
                        <li> 국민을 무시(개,돼지)하고 막말을 하고, 성추행을 하고, 술마시고 성폭해 하는 인간들을 기억합시다. </li>
                        
                      </ul>
                    </div>
                </div>
            </div>

            <div class='col-md-12'>
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5> 사이트 운영의 철학 </h5>
                    </div>
                    <div class="ibox-content">
                      <ul style="padding: 10px">  
                        <li> 반드시 근거가 있는 것을 근거로 합니다. 즉 근거는 인터넷에 있는 객관적 자료을 기반으로 한다는 것입니다.</li>
                        <li> 남을 비난 하는 것이 목적이 아니고, 잘못된 행위를 기억하자를 것입니다. 따라서 비난은 삼가해 주시기 바랍니다. </li>
                        <li> 그래서 실명으로 냉정하고 정확한 내용만 작성을 해 주시기 바랍니다. </li>
                        
                      </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}


{% block javascript %}
<script>
    $(function(){

        $('.form-group label').addClass('col-sm-2');
        $('.form-group input, .form-group textarea').addClass('form-control');

        $('.btn-url').click(function(){
            $('body').addClass('wait');
        });
    });
</script>
{% endblock javascript %}

mySite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} 역사를 잊은 민족에게 미래는 없다. {% endblock title %} </title>
    <link href="{% static 'css/vendor/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/topsearch.css' %}" rel="stylesheet">

</head>  

<body>
    <div id="wrapper">

        <!--  Left Menu -->
        {% include "left_menu.html" %}

        <!-- Right Content --> 
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                
                <!--  Top Search -->
                    {% include 'top_search.html' %}

                <!--  Top Search -->
                    {% include 'top_menu.html' %}
                </nav>
            </div>

            <!-- Main Title -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-md-12">
                {% block  header-index %}
                
                {% endblock header-index %}
                </div> <!-- col-md-12 -->
            </div>

            <!-- BODY Content -->
            <div class="wrapper wrapper-content animated fadeIn">
                <div class="row animated fadeInDown">
                    
                    <!-- MAIN  -->
                    <div class="col-md-10">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}} alert-dismissable" role="alert">
                                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"><span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    
                    {% block content %}

                    {% endblock content %}
                    </div> 
                    
                    <!--  RIGHT SIDE -->
                    <div class="col-md-2">
                    {% block right_side %}

                    {% endblock right_side %}
                    </div>
                </div>
            </div>
            
            <div class="wrapper wrapper-content animated fadeIn blank">
            </div>
            <!-- FOOTER -->
            <div class="footer">
                {% include 'footer.html' %}
            </div>
        </div>
    </div>

    <!-- Mainly scripts --> 
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/topmenu.js' %}"></script>

    <!-- Custom and plugin javascript -->
    {% block javascript %}        
    {% endblock javascript %}
</body>

</html>

mySite/templates/footer.html
<div class="pull-right">
    Email : <a href="mailto:IRememberYourPast@gmail.com" target="_top">IRememberYourPast@gmail.com</a>
</div>
<div class='col-sm-6'>
    <strong>Copyright</strong> I Remember Your Past &copy; Since 2017
</div>

mySite/templates/left_menu.html
{% load static %}        
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
    <!-- Main Menu -->
        <ul class="nav metismenu" id="side-menu">
        {% if user.is_authenticated %}
            <li class="nav-header">
                <div class="dropdown profile-element"> 
                    <span>
                        <img alt="image" class="img-circle" src="{% if user.profile.picture %} {{ user.profile.picture.url }}{% else %} {% static 'images/nouser.png' %}{% endif %}" width="150">
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> 
                            <span class="text-muted text-xs block">{{user.first_name}} <b class="caret"></b></span> 
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url 'authentication:profile_edit' %}">Profile</a></li> 
                        <li class="divider"></li>
                        <li><a href="{% url 'authentication:password' %}">비밀번호변경</a></li> 
                        <li class="divider"></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li> 
                    </ul>
                
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
        {% else %}
            <li>
                <a href="{% url 'login' %}"> 
                    <i class="fa fa-th-large"></i> 
                    <span class="nav-label">I Remember Your Past</span> 
                    <span class="fa arrow"></span>
                </a>
            </li>
        {% endif %}
            
            <li>
                <a href="{% url 'records:person_list' %}"><i class="fa fa-user"></i> <span class="nav-label">기억할 사람들</span></a> 
            </li>

            <li>
                <a href="{% url 'records:check_person' %}"><i class="fa fa-th-large"></i> <span class="nav-label">사람 등록</span></a> 
            </li>
            <li>
                <a href="{% url 'records:event_list' %}"><i class="fa fa-flask"></i> <span class="nav-label">사건 목록</span></a> 
            </li>
            <li>
                <a href="{% url 'calendars:event_list' %}"><i class="fa fa-calendar"></i> <span class="nav-label">달력</span></a> 
            </li>
            <li>
                <a href="{% url 'mistake:add_report' %}"><i class="fa fa-desktop"></i> <span class="nav-label">오류 보고</span></a> 
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Graphs</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="graph_flot.html">Flot Charts</a></li>
                    <li><a href="graph_morris.html">Morris.js Charts</a></li>
                    <li><a href="graph_rickshaw.html">Rickshaw Charts</a></li>
                    <li><a href="graph_chartjs.html">Chart.js</a></li>
                    <li><a href="graph_chartist.html">Chartist</a></li>
                    <li><a href="c3.html">c3 charts</a></li>
                    <li><a href="graph_peity.html">Peity Charts</a></li>
                    <li><a href="graph_sparkline.html">Sparkline Charts</a></li>
                </ul>
            </li>

            <li class="landing_link">
                <a href="{% url 'records:person_table' %}"><i class="fa fa-database"></i> <span class="nav-label">사용자 TABLE</span></a>
            </li>
            <li class="landing_link">
                <a href="{% url 'records:aboutUS' %}"><i class="fa fa-database"></i> <span class="nav-label">About us</span></a>
            </li> 
        </ul>
    </div>
</nav>

mySite/templates/right_side.html
<div class="ibox float-e-margins">
    <div class="ibox-content mailbox-content">
        <div class="file-manager">
            <h5>Popular Person</h5>
            <ul class="folder-list m-b-md" style="padding: 0">
        {% for key, obj in request.session.pop_persons.items %}  
                <li><a href="{% url 'records:person_detail' obj.id %}"> <i class="fa fa-inbox "></i> {{obj.name}} <span class="label label-warning pull-right"> {{obj.following}} </span> </a></li>
        {% endfor %}
            </ul>

           <h5>New Person</h5>
            <ul class="folder-list m-b-md" style="padding: 0">
        {% for key, obj in request.session.new_persons.items %}  
                <li><a href="{% url 'records:person_detail' obj.id %}"> <i class="fa fa-inbox "></i> {{obj.name}} <span class="label label-warning pull-right"> {{obj.following}} </span> </a></li>
        {% endfor %}
            </ul>

            <h5 class="tag-title">Tags</h5>
            <ul class="tag-list" style="padding: 0">
        {% for tag, count in request.session.popular_tags %}
                <li><a href="{% url 'records:tag' tag type %}"><i class="fa fa-tag"></i> {{ count }} {{ tag }}</a></li> 
        {% endfor %}
            </ul>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

mySite/templates/title.html
<h2>역사를 잊은 민족에게 미래는 없다.</h2>

mySite/templates/top_search.html
<div class="navbar-header">
    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
    <form role="search" class="navbar-form-custom">
        <div class="form-group top_search">
            {% csrf_token %}
            <input type="text" placeholder="검색하고자 하는 단어를 입력하세요...." class="form-control" name="top_search" id="top_search" style="width:200px">
            <div class="top_results" id="top_results">
              
            </div>
        </div> 
    </form>
</div>