mySite/records/urls.py
# records/urls.py
"""records URL Configuration"""
from django.conf.urls import url
from . import views, views_reg, views_news

urlpatterns = [
    url(r'^$', views.person_list, name='person_list'),
    url(r'^ajax_person_list/', views.ajax_person_list, name='ajax_person_list'),
    url(r'^table/$', views.person_table, name='person_table'),
    url(r'^persondetail/(?P<person_id>\d+)/$', views.person_detail, name='person_detail'),
    url(r'^personrelationship/(?P<person_id>\d+)/$', views.person_relationship, name='person_relationship'),
    url(r'^event_list/$', views.event_list, name='event_list'),
    url(r'^personfamily/(?P<person_id>\d+)/$', views.person_family, name='person_family'),
    url(r'^event_detail/(?P<event_id>\d+)/$', views.event_detail, name='event_detail'),

    url(r'^check_person/$', views_reg.check_person, name='check_person'),
    url(r'^add_person/$', views_reg.add_person, name='add_person'),
    url(r'^edit_person/(?P<person_id>\d+)/$', views_reg.edit_person, name='edit_person'),

    url(r'^check_event/(?P<person_id>\d+)/$', views_reg.check_event, name='check_event'),
    url(r'^add_event/(?P<person_id>\d+)/$', views_reg.add_event, name='add_event'),
    url(r'^person_event_matching/(?P<person_id>\d+)/$', views_reg.person_event_matching, name='person_event_matching'),

    url(r'^check_evidence/(?P<personevent_id>\d+)/$', views_reg.check_evidence, name='check_evidence'),
    url(r'^add_evidence/$', views_reg.add_evidence, name='add_evidence'),
# 9월 21일 추가함
    url(r'^evidence_add_person/(?P<news_id>\d+)/(?P<event_id>\d+)/$', views_reg.evidence_add_person, name='evidence_add_person'),

# 10/28 
    url(r'^add_event_news/(?P<event_id>\d+)/$', views_news.add_event_news, name='add_event_news'),

    url(r'^ajax_person_like/(?P<person_id>\d+)/$', views.ajax_person_like, name='ajax_person_like'),
    url(r'^ajax_person_following/(?P<person_id>\d+)/$', views.ajax_person_following, name='ajax_person_following'),

    url(r'^ajax_event_like/(?P<event_id>\d+)/$', views.ajax_event_like, name='ajax_event_like'),
    url(r'^ajax_event_following/(?P<event_id>\d+)/$', views.ajax_event_following, name='ajax_event_following'),

    url(r'^tag/(?P<tag_name>\w+)/(?P<type>\w+)/$', views.tag, name='tag'),
    url(r'^top_search/$', views.top_search, name='top_search'),

    url(r'^register_relation/(?P<person_id>\d+)/$', views.register_relation, name='register_relation'),
    url(r'^search_persons/$', views.search_persons, name='search_persons'),

    url(r'^aboutUS/$', views.aboutUS, name='aboutUS'),

]

mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as login_views
from django.conf.urls.static import static
from django.shortcuts import redirect

from mySite.authentication import views as signup_views

urlpatterns = [
    url('^$', lambda r: redirect('/records/'), name='home'),
    url(r'^xmlyoon/', admin.site.urls),
    url(r'^master/', include('mySite.master.urls', namespace='master')),
    url(r'^records/', include('mySite.records.urls', namespace='records')),
    url(r'^authentication/', include('mySite.authentication.urls', namespace='authentication')),
    url(r'^mistake/', include('mySite.mistake.urls', namespace='mistake')),
    url(r'^comments/', include('mySite.comments.urls', namespace='comments')),
    url(r'^activity/', include('mySite.activity.urls', namespace='activity')),
    url(r'^nickname/', include('mySite.nickname.urls', namespace='nickname')),
    url(r'^calendars/', include('mySite.calendars.urls', namespace='calendars')),

    url(r'^accounts/', include('allauth.urls')),
    # url(r'^evidence/', include('evidence.urls', namespace='evidence')),

    url(r'^signup/$', signup_views.signup, name='signup'),
    url(r'^login', login_views.login, {'template_name': 'authentication/login.html'},
        name='login'),
    url(r'^logout', signup_views.logout, name='logout'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mySite/records/forms.py
# records/forms.py

from PIL import Image
from django import forms
from django.forms import Textarea

# Create your forms here.
from mySite.master.models import Job
from .models import Person, Event, Evidence, Tag

class PersonForm(forms.ModelForm):
    jobs = forms.ModelMultipleChoiceField(queryset=Job.objects.all(), 
            widget=forms.CheckboxSelectMultiple)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple)
    x = forms.FloatField(widget=forms.HiddenInput(),required=False)
    y = forms.FloatField(widget=forms.HiddenInput(),required=False)
    width = forms.FloatField(widget=forms.HiddenInput(),required=False)
    height = forms.FloatField(widget=forms.HiddenInput(),required=False)
    picture = forms.FileField(required=False)

    class Meta:
        model = Person
        fields = ['name', 'nick_name', 'birth_year', 'jobs', 'picture', 'url', 'x', 'y', 'width', 'height', ]
        widgets = {
            'picture': forms.FileInput(attrs={
                'accept': 'image/*'  # this is not an actual validation! don't rely on that!
            })
        }

    # def __init__(self):
    #     super(PersonForm, self).__init__(*args, **kwargs)
    #     self.fields['tags'].initial=(tag.id for tag in Tag.objects.filter())

    def save(self):
        person = super(PersonForm, self).save()

        if not person.picture:
            return person 

        x = self.cleaned_data.get('x', 0)
        if not x:
            return person

        y = self.cleaned_data.get('y')
        width = self.cleaned_data.get('width')
        height = self.cleaned_data.get('height')

        image = Image.open(person.picture)
        cropped_image = image.crop((x, y, width+x, height+y))
        resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
        resized_image.save(person.picture.path)

        return person


class EventForm(forms.ModelForm):
    person = forms.IntegerField(widget=forms.HiddenInput())
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Tag을 입력해 주세요.'}),
                            help_text='입력할 때 ,을 이용해 구분해 주시기 바랍니다.')
    class Meta:
        model = Event
        fields = ['name', 'content', 'category', 'person']
        widgets = {
            'content': Textarea(attrs={'rows': 3}),
        }

class EvidenceForm(forms.Form):
    url = forms.URLField()


class PersonEvidenceForm(forms.ModelForm):
    personevent = forms.IntegerField(widget=forms.HiddenInput())
    news = forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = Evidence
        fields = ['personevent', 'news']

mySite/records/views.py
# records/views.py
from datetime import timedelta, datetime
# from django.utils import timezone

from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.db.models import Count

from .models import Person, PersonEvent, Event, Tag, Relationship

# Create your views here.
def check_session(request):

    now = datetime.now()
    if 'popular_tags' in request.session:
        dt, _ = request.session.get('reg_time').split('.')
        reg_time = datetime.strptime(dt, '%Y-%m-%d %H:%M:%S') + timedelta(days=1)
        if now < reg_time:
            return False
  
    request.session.set_expiry(int(timedelta(days=365).total_seconds()))
    request.session['popular_tags'] = Tag.get_person_popular_tags()
    request.session['pop_persons'] = Person.get_persons_following()
    request.session['new_persons'] = Person.get_new_persons()
    request.session['reg_time'] = str(now)
    print(str(now))
    return True


def _person_list(request, person_list, template='records/person_list.html'):
    
    paginator = Paginator(person_list, 6)
    page = request.GET.get('page')

    try:
        person_list = paginator.page(page)
    except PageNotAnInteger:
        person_list = paginator.page(1)
    except EmptyPage:
        person_list = paginator.page(paginator.num_pages)

    check_session(request)
    context = {'person_list': person_list}
    return render(request, template, context)


def person_list(request):
    person_list = Person.objects.annotate(
            num_following=Count('following')).filter(status='P').order_by('-num_following')
    return _person_list(request, person_list)

def ajax_person_list(request):
    person_list = Person.objects.annotate(
            num_following=Count('following')).filter(status='P').order_by('-num_following')
    return _person_list(request, person_list, 
            template='records/partial/partial_person_list.html')

def person_table(request):
    person_list = Person.objects.prefetch_related('tags', 'jobs').filter(status='P')
    
    context = {'person_list': person_list}
    return render(request, 'records/person_table.html', context)

def person_detail(request, person_id):
    person = Person.objects.select_related('created_user').prefetch_related(
            'tags', 'jobs', 'personevent_set__event', 'personevent_set__evidence_set__news', 
            'user_like', 'following').get(id=person_id)
    # personevent_list = PersonEvent.objects.select_related('event', 'person').filter(person=person).all()
    check_session(request)
    context = { 'person': person }
    return render(request, 'records/person_detail.html', context)


def person_relationship(request, person_id):
    person = Person.objects.select_related('created_user').prefetch_related(
            'tags', 'jobs', 'personevent_set__event', 'personevent_set__evidence_set__news', 
            'user_like', 'following').get(id=person_id)
    # personevent_list = PersonEvent.objects.select_related('event', 'person').filter(person=person).all()
    check_session(request)
    context = { 'person': person }
    return render(request, 'records/person_relationship.html', context)


def person_family(request, person_id):
    person = Person.objects.select_related('created_user').prefetch_related(
            'tags', 'jobs', 'personevent_set__event', 'personevent_set__evidence_set__news', 
            'user_like', 'following').get(id=person_id)
    # personevent_list = PersonEvent.objects.select_related('event', 'person').filter(person=person).all()
    check_session(request)
    context = { 'person': person, }
    return render(request, 'records/person_family.html', context)

# Create your views here.
def _event_list(request, event_list):
    paginator = Paginator(event_list, 6)
    page = request.GET.get('page')

    try:
        event_list = paginator.page(page)
    except PageNotAnInteger:
        event_list = paginator.page(1)
    except EmptyPage:
        event_list = paginator.page(paginator.num_pages)
    check_session(request)
    context = { 'event_list': event_list }

    return render(request, 'records/event_list.html', context)

def event_list(request):
    event_list = Event.objects.prefetch_related('tags', 'user_like', 
            'following').select_related('category', 'created_user').annotate(
            related_person=Count('personevent')).order_by('-related_person')
    return _event_list(request, event_list)

def event_detail(request, event_id):
    event = Event.objects.select_related('category').get(id=event_id)
    personevent_list = PersonEvent.objects.select_related('person').filter(event=event).all()
    check_session(request)
    context = { 'event': event, 'personevent_list': personevent_list }
    return render(request, 'records/event_detail.html', context)


############################
# Person
############################
@login_required
@require_http_methods(["POST"])
def ajax_person_like(request, person_id):
    data = dict()
    user = request.user
    # person_id = request.POST.get('personid')
    person = get_object_or_404(Person, id=person_id)
    user_list = person.user_like.all()
    
    if user in user_list :
        person.user_like.remove(user)
        data['like'] = 'like'
        user.profile.notify_person_unliked(person)
    else:
        person.user_like.add(user)
        data['like'] = 'unlike'
        user.profile.notify_person_liked(person)

    data['status'] = True
    data['total_likes'] = person.total_likes

    return JsonResponse(data)    


@login_required
@require_http_methods(["POST"])
def ajax_person_following(request, person_id):
    data = dict()
    user = request.user

    person = get_object_or_404(Person, id=person_id)
    user_list = person.following.all()
    
    if user in user_list :
        person.following.remove(user)
        data['follow'] = 'following'
        data['message'] = '{} 님 지켜 보기을 취소하셨습니다.'.format(person.name)
        user.profile.notify_person_unfollowing(person)
    else:
        person.following.add(user)
        data['follow'] = 'unfollowing'
        data['message'] = '{} 님 지켜 보기를 신청하셨습니다.'.format(person.name)
        user.profile.notify_person_following(person)

    data['status'] = True
    data['total_following'] = person.total_following

    return JsonResponse(data)    


############################
# Event
############################
@login_required
@require_http_methods(["POST"])
def ajax_event_like(request, event_id):
    data = dict()
    # event_id = request.POST.get('eventid')
    event = get_object_or_404(Event, id=event_id)
    user_list = event.user_like.all()
    
    if request.user in user_list :
        event.user_like.remove(request.user)
        data['like'] = 'like'
    else:
        event.user_like.add(request.user)
        data['like'] = 'unlike'

    data['status'] = True
    data['total_likes'] = event.total_likes

    return JsonResponse(data)    


@login_required
@require_http_methods(["POST"])
def ajax_event_following(request, event_id):
    data = dict()
    
    event = get_object_or_404(Event, id=event_id)
    user_list = event.following.all()
    
    if request.user in user_list :
        event.following.remove(request.user)
        data['follow'] = 'following'
        data['message'] = '사건 "{}" 지켜 보기 취소하셨습니다.'.format(event.name)
    else:
        event.following.add(request.user)
        data['follow'] = 'unfollowing'
        data['message'] = '사건 "{}" 지켜 보기를 신청하셨습니다.'.format(event.name)

    data['status'] = True
    data['total_following'] = event.total_following

    return JsonResponse(data)    


############################
# Tag
############################
def tag(request, tag_name, type):
    tag = Tag.objects.get(tag=tag_name)
    if type == 'P':
        person_list = tag.person_set.all() 
        return _person_list(request, person_list)
    else:
        event_list = tag.event_set.all() 
        return _event_list(request, event_list)


############################
# Register Relationship
############################
def register_relation(request, person_id):

    me = Person.objects.get(id = person_id)
    message = ""

    if request.method == "POST":
        parent_id = request.POST.get('parent_id')
        spouse_id = request.POST.get('spouse_id')
        children_id = request.POST.getlist('children_id')

        if parent_id:
            ptype = request.POST.get('ptype')
            other = Person.objects.get(id = parent_id)
            Relationship.objects.create(person=me, other=other, relationship='parent', ctype=ptype)
            message += "{} 님이 부모님으로 추가되었습니다. <br>".format(other.name)

        if spouse_id:
            stype = request.POST.get('stype')
            other = Person.objects.get(id = spouse_id)
            Relationship.objects.create(person=me, other=other, relationship='spouse', ctype=stype)
            Relationship.objects.create(person=other, other=me, relationship='spouse', ctype=stype)
            message += "{} 님이 아내또는 남편으로 추가되었습니다. <br>".format(other.name)

        if children_id:
            for child in children_id:
                other = Person.objects.get(id = child)
                ctype = '아버지' if other.sex == 'M' else '어머니'
                Relationship.objects.create(person=other, other=me, relationship='parent', ctype=ctype)
                message += "{} 님이 아들 또는 딸로 추가되었습니다. <br>".format(other.name)

        if parent_id or spouse_id or children_id:
            messages.success(request, message)
            return redirect('records:person_relationship', person_id)
        else:

mySite/records/templates/records/partial/event_persons.html
{% load static %}

    {# list #}
    <div class="col-sm-6">
        <div class="ibox row">
            <div class="col-sm-6">
                <div class="text-center">
                    <a href="{% url 'records:person_detail' person.id %}">
                    <img alt="image" width='200' class="img-circle m-t-xs img-responsive" src="{% if person.picture %}{{ person.picture.url }}{% else %}
                    {% static 'images/nouser.png' %}{% endif %}
                    "> </a>
                </div>
            </div>
            <div class="col-sm-6">
                <a href="{% url 'records:person_detail' person.id %}">
                    <h4><strong>{{ person.name }}</strong></h4>
                </a>
                <p><i class="fa fa-map-marker"></i> {{ person.nick_name }} </p>
                <p><i class="fa fa-calendar"></i> Birth Year : {{ person.birth }}</p>
                <p><i class="fa fa-flag"></i> Jobs :
                    {{person.jobs.all|join:", "}}
                </p>
                <p><i class="fa fa-pencil"></i> Tags :
                    {{person.tags.all|join:", "}}
                </p>
            </div>
            
        </div>
    </div>

mySite/records/templates/records/partial/partial_person_list.html
{% load static %}

{% for person in person_list %}
    <div class="col-md-6 person">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <a href="{% url 'records:person_detail' person.id %}">
                    <strong>{{ person.name }}</strong>
                </a>
            </div>

            <div class="ibox-content">
                <div class="col-sm-6">
                    <div class="text-center">
                        <a href="{% url 'records:person_detail' person.id %}">
                        <img alt="image" class="img-circle m-t-xs img-responsive" width='200px' src="{% if person.picture %} {{ person.picture.url }} {% else %} {% static 'images/nouser.png' %}{% endif %}"></a>
                    </div>
                </div>
                <div class="col-sm-6">
                    
                    <p><i class="fa fa-map-marker"></i> {{ person.nick_name }} </p>
                    <p> Birth Year : {{ person.birth_year }}</p>
                    <p> Jobs :
                    {{person.jobs.all|join:", "}}
                    </p>
                    <p> Tags :
                    {{person.tags.all|join:", "}}
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div> {# class="col-md-6" #}

{% endfor %}

mySite/records/templates/records/partial/person_info.html
{% load static %}
<!-- 개인 정보 -->
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5> {{person.name}} <small> 인물 상세정보</small></h5>
        {% if not checkbox %}
            <div class="ibox-tools person">
                <a class="collapse-link person-information">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                   <!-- <li><a class='following' href="">Following</a></li> -->
                {% if user.is_staff %}
                    <li><a class='edit' href="{% url 'records:edit_person' person.id %}">정보 수정</a></li> 
                {% endif %}
                </ul> 
            </div>
        {% endif %}
    </div>
    <div class="ibox-content">
        <div class="no-padding">
            <img alt="image" class="img-responsive" src="{% if person.picture %}{{ person.picture.url }}
            {% else %}{% static 'images/nouser.png' %}{% endif %}">
        </div>    
        <div class="ibox-content no-padding profile-content">

            {# 해당 Person 본인 정보 #}
            <div class="media-body no-padding">
                {% if checkbox %}
                    <input type="checkbox" checked value="{{person.id}}" name="person" class="checkbox checkbox-primary pull-right">
                {% endif %}
                <p><i class="fa fa-flag-o"></i> {{ person.nick_name }} </p>
                <p><i class="fa fa-calendar"></i> {{ person.birth_year }} 년</p>
                <p><i class="fa fa-flag"></i> Jobs :
                    {{person.jobs.all|join:", "}}
                </p>
                {% if  person.url %}
                <a href="{{ person.url }}" target="remember">
                    <p><i class="fa fa-id-badge"></i> <b> 상세 내용 : 위키 또는 나무 </b></p>
                </a>
                {% endif %}
                <p><i class="fa fa-pencil"></i> Tags :
                    {{person.tags.all|join:", "}}
                </p>
            </div>

        {% with total_likes=person.user_like.count total_following=person.following.count users_like=person.user_like.all users_following=person.following.all %}
            <div class="actions"> 
                <button class="btn btn-outline btn-primary btn-xs btnPersonLike">
                     {% if request.user not in users_like %}<i class="fa fa-heart-o"></i>{% else %}<i class="fa fa-heart"></i>{% endif %}
                    <span class="count">(<span class="likes">{{total_likes}}</span>)</span>
                </button>
                <button class="btn btn-primary btn-xs btnPersonFollowing">
                    {% if request.user not in users_following %}Follow{% else %}<i class="fa fa-thumbs-up"></i>following{% endif %}
                    <span class="count">(<span class="follow"> {{total_following}} </span>)</span>
                </button>
                <button class="btn btn-outline btn-primary btn-xs"><i class="fa fa-share"></i> Share</button>
                <a href="{% url 'records:person_relationship' person.id %}" class="btn btn-primary btn-xs"> 
                    <i class="fa fa-users"></i>가족
                </a>
            </div>
        {% endwith %}

        </div>
    </div>
</div>

<!-- 별명 짓기 -->
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>{{ person.name }}에게 어울리는 호칭은?</h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
        </div>
    </div>
    <div class="ibox-content nicklist" style="padding:0 10px 5px 10px;">
        <ul class="todo-list m-t small-list nickname_list">
            <!-- 별명 목록과 별명에 대한 평가 ajax -->
            {% include 'nickname/partial/nicknames.html' with personnick_list=person.get_nicknames %}

            {% if person.get_total_nick >= 5 %}
                <button class="btn b-r-md btn-primary btn-block btn-outline" id="NickMore">더 보기...</button>
            {% else %}
                <h4>새로운 호칭 제안</h4>
                <form action="" method="POST" id="formCreateNick"> 
                    {% csrf_token %}
                    <div class="input-group search">
                        <input type="text" name="nickname" class="form-control" id="id_nickname">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-primary" id="btnCreateNick">Go!</button>
                            </span>
                        </input>
                        <div class="results" id="nickname_results">
                          
                        </div>
                    </div>
                    <div class="row made-input">
                        <div class="col-xs-4" id="nickname_name">
                            
                        </div>
                        <div class="col-xs-2" id="nickname_id">
                            
                        </div>
                    </div>
                </form>
            {% endif %}
        </ul>
    </div>
</div>

<!-- 가족 관계 -->
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>가족 관계</h5>
        <div class="ibox-tools family">
            <a class="collapse-link family-relationship">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
        </div>
    </div>
    <div class="ibox-content">
    {# SPOUSE 남편/아내 #}
    {% if person.get_spouse %}
        <div class="ibox-content no-padding profile-content">
        {% for spouse in person.get_spouse %}
            {% include 'records/partial/relationship.html' with person=spouse relationship='남편/아내' checkbox=False %}
        {% endfor %}
        </div>
    {% endif %}

    {# PARENT #}
    {% if person.get_parent %}
        <div class="ibox-content no-padding profile-content">
            {% for parent in person.get_parent %}
                {# 아버지/어머니 #}
                {% include 'records/partial/relationship.html' with person=parent relationship='부모' checkbox=False %} 
            {% endfor %}
        </div>
    {% endif %}

    {# 자식들 #}
    {% if person.get_children %}
        <div class="ibox-content no-padding profile-content">
            <div class="row">
        {% for child in person.get_children %}
            {% include 'records/partial/relationship.html' with person=child relationship='자식' checkbox=False %}
        {% endfor %}
            </div>
        </div>
    {% endif %}
    </div>
</div>

mySite/records/templates/records/partial/person_info_for_menspouse.html
{% load static %}
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5> {{ relationship }} </h5>
        {% if checkbox %}
            <div class="ibox-tools">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a class='following' href="">Following</a></li> 
                </ul> 
            </div>
        {% endif %}
    </div>

    {# 조상 반복 #}
    <div class="ibox-content">
        {# 본인 #}
        {% include 'records/partial/relationship_of_person.html' with obj=person  %}
        {# 아내 또는 남 #}
        {% for person in person.get_spouse %}
            {% include 'records/partial/relationship_of_person.html' with obj=person %}
        {% endfor %}

        {% for sibling in person.get_sibling %}
            {% if sibling != person %}
                {% include 'records/partial/relationship_of_person.html' with obj=sibling %}
            {% endif %}
        {% endfor %}

    {% if user.is_staff and register %}
        <div class="col-sm-3">
            <div class="no-padding">
                {% if user.is_authenticated %}
                    <button class="btn btn-primary createRelation">가족 관계 등록</button> <br>
                    <!-- 
                    <a class="btn btn-primary" href="{% url 'records:person_family' person.id %}"> 
                        가족 전체 관계 보기
                    </a> 
                    -->  
                {% endif %}
            </div>
        </div>        
    {% endif %}

    </div>
</div>

mySite/records/templates/records/partial/relationship.html
{% load static %}

{% if forloop.first and display %}
    <h3><strong> {{ relationship }}</strong></h3>
{% endif %}
<div class="media-body">
    <div class="no-padding">
        <a href="{% url 'records:person_detail' person.id %}">
            <img alt="image" class="img-responsive" width="50%" src="{% if person.picture %}{{ person.picture.url }}{% else %}{% static 'images/nouser.png' %}{% endif %}" style="max-width: 100px;">
        </a>
    </div>    
    <div class="media-body ">
        <h4>
            <a href="{% url 'records:person_detail' person.id %}">
                <strong>{{ person.name }}</strong> 
            </a>
            <a href="{% url 'records:person_relationship' person.id %}">
                <small>관계 {{ relation }} </small>
            </a>
        </h4>

        <p>
            <i class="fa fa-flag"></i> {{person.nick_name}}
        </p>

        {% if checkbox %}
            <input type="checkbox" checked value="{{person.id}}" name="parent" class="checkbox checkbox-primary pull-right">
        {% endif %}
        <p><i class="fa fa-calendar"></i> {{ person.birth_year }} 년</p>
        <!--
        <p><i class="fa fa-flag"></i> Jobs :
            {{person.jobs.all|join:", "}}
        </p>
        -->
    </div>
</div>

mySite/records/templates/records/partial/relationship_of_person.html
{% load static %}
<div class="col-lg-2 col-md-3 col-sm-4">
    <div class="no-padding">
        <a href="{% url 'records:person_detail' obj.pk %}">
            <img alt="image" width="100px" class="img-responsive" src="{% if obj.picture %}{{ obj.picture.url }}
        {% else %}{% static 'images/nouser.png' %}{% endif %}">
        </a>
    </div>    
    <div class="ibox-content no-padding profile-content">

        {# 해당 Person 본인 정보 #}
        <div class="media-body ">
            <h4>
                <a href="{% url 'records:person_detail' obj.id %}">
                    <strong>{{ obj.name }}</strong> 
                </a>
                <a href="{% url 'records:person_relationship' obj.id %}">
                    <small>관계 {{ relation }} </small>
                </a>
            </h4>
            
            <p><i class="fa fa-flag"></i> {{obj.nick_name}}</p>
            <p>부:{{obj.get_father}} 모:{{obj.get_mother}}</p>
            {% if checkbox %}
                <input type="checkbox" checked value="{{obj.id}}" name="person" class="checkbox checkbox-primary pull-right">
            {% endif %}
            <p><i class="fa fa-calendar"></i> {{ obj.birth_year }} 년 </p>
            <p><i class="fa fa-flag"></i> Jobs :
                {{obj.jobs.all|join:", "}}
            </p>
            
        </div>
    </div>

    {# 손자들 #}
    {% if obj.get_children and family %}
        <div class="ibox-content no-padding profile-content">
        {% for children in obj.get_children %}
            {% include 'records/partial/relationship.html' with person=children relationship='손자' display=True %}
        {% endfor %}
        </div>
    {% endif %}

    {# 증손자들 #}
    {% if obj.get_children and family %}
        <h4>증손자</h4>
        {% for children in obj.get_children %}
            {% for children in children.get_children %}
                {% include 'records/partial/relationship.html' with person=children relationship='증손자' %}
            {% endfor %}
        {% endfor %}
    {% endif %}    

</div>