mySite/records/urls.py
# records/urls.py
"""records URL Configuration"""
from django.conf.urls import url
from . import views, views_reg, views_news

urlpatterns = [
    url(r'^$', views.person_list, name='person_list'),
    url(r'^ajax_person_list/', views.ajax_person_list, name='ajax_person_list'),
    url(r'^table/$', views.person_table, name='person_table'),
    url(r'^persondetail/(?P<person_id>\d+)/$', views.person_detail, name='person_detail'),
    url(r'^personrelationship/(?P<person_id>\d+)/$', views.person_relationship, name='person_relationship'),
    url(r'^event_list/$', views.event_list, name='event_list'),
    url(r'^personfamily/(?P<person_id>\d+)/$', views.person_family, name='person_family'),
    url(r'^event_detail/(?P<event_id>\d+)/$', views.event_detail, name='event_detail'),

    url(r'^check_person/$', views_reg.check_person, name='check_person'),
    url(r'^add_person/$', views_reg.add_person, name='add_person'),
    url(r'^edit_person/(?P<person_id>\d+)/$', views_reg.edit_person, name='edit_person'),

    url(r'^check_event/(?P<person_id>\d+)/$', views_reg.check_event, name='check_event'),
    url(r'^add_event/(?P<person_id>\d+)/$', views_reg.add_event, name='add_event'),
    url(r'^person_event_matching/(?P<person_id>\d+)/$', views_reg.person_event_matching, name='person_event_matching'),

    url(r'^check_evidence/(?P<personevent_id>\d+)/$', views_reg.check_evidence, name='check_evidence'),
    url(r'^add_evidence/$', views_reg.add_evidence, name='add_evidence'),
# 9월 21일 추가함
    url(r'^evidence_add_person/(?P<news_id>\d+)/(?P<event_id>\d+)/$', views_reg.evidence_add_person, name='evidence_add_person'),

# 10/28 
    url(r'^add_event_news/(?P<event_id>\d+)/$', views_news.add_event_news, name='add_event_news'),

    url(r'^ajax_person_like/(?P<person_id>\d+)/$', views.ajax_person_like, name='ajax_person_like'),
    url(r'^ajax_person_following/(?P<person_id>\d+)/$', views.ajax_person_following, name='ajax_person_following'),

    url(r'^ajax_event_like/(?P<event_id>\d+)/$', views.ajax_event_like, name='ajax_event_like'),
    url(r'^ajax_event_following/(?P<event_id>\d+)/$', views.ajax_event_following, name='ajax_event_following'),

    url(r'^tag/(?P<tag_name>\w+)/(?P<type>\w+)/$', views.tag, name='tag'),
    url(r'^top_search/$', views.top_search, name='top_search'),

    url(r'^register_relation/(?P<person_id>\d+)/$', views.register_relation, name='register_relation'),
    url(r'^search_persons/$', views.search_persons, name='search_persons'),

    url(r'^aboutUS/$', views.aboutUS, name='aboutUS'),

]

mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as login_views
from django.conf.urls.static import static
from django.shortcuts import redirect

from mySite.authentication import views as signup_views

urlpatterns = [
    url('^$', lambda r: redirect('/records/'), name='home'),
    url(r'^xmlyoon/', admin.site.urls),
    url(r'^master/', include('mySite.master.urls', namespace='master')),
    url(r'^records/', include('mySite.records.urls', namespace='records')),
    url(r'^authentication/', include('mySite.authentication.urls', namespace='authentication')),
    url(r'^mistake/', include('mySite.mistake.urls', namespace='mistake')),
    url(r'^comments/', include('mySite.comments.urls', namespace='comments')),
    url(r'^activity/', include('mySite.activity.urls', namespace='activity')),
    url(r'^nickname/', include('mySite.nickname.urls', namespace='nickname')),
    url(r'^calendars/', include('mySite.calendars.urls', namespace='calendars')),

    url(r'^accounts/', include('allauth.urls')),
    # url(r'^evidence/', include('evidence.urls', namespace='evidence')),

    url(r'^signup/$', signup_views.signup, name='signup'),
    url(r'^login', login_views.login, {'template_name': 'authentication/login.html'},
        name='login'),
    url(r'^logout', signup_views.logout, name='logout'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mySite/records/models.py
# records/models.py
import csv
import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Count
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.shortcuts import get_object_or_404

from mySite.master.models import Job, Region, EventCategory, Media
from mySite.nickname.models import Nickname

# Create your models here.


class Person(models.Model):
    """docstring for Person"""
    """ 기억할 인물에 대한 설명 """
    MALE = 'M'
    FEMALE = 'F'
    SEX = (
        (MALE, '남'),
        (FEMALE, '여'),
    )

    DRAFT = 'D'
    PUBLISHED ='P'
    WITHDRAWN = 'W'
    STATUS_CHOICES = (
        (DRAFT, '초안'),
        (PUBLISHED, '공개'),
        (WITHDRAWN, '철회'),
    )
    name = models.CharField(max_length=50)
    nick_name = models.CharField(max_length=50, verbose_name='별칭', null=True, blank=True)
    birth_year = models.IntegerField(null=True, verbose_name='출생년도', blank=True)
    sex = models.CharField(max_length=1, choices=SEX, default=MALE)
    jobs = models.ManyToManyField(Job, blank=True)
    picture = models.ImageField(upload_to='person_picture/%Y/%m/', null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    regions = models.ManyToManyField(Region, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=DRAFT)
    created_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='person_liked', blank=True)
    following = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='person_follow', blank=True)
    created_date = models.DateTimeField(auto_now_add=True,null=True, blank=True)

    # class Meta:
    #     ordering = ['name',]

    def __str__(self):
        return self.name

    @staticmethod
    def get_persons_following():
        pop_persons = {}
        count = 0
        persons = Person.objects.annotate(num_following=Count('following')).order_by('-num_following')
        for person in persons:
            pop_persons[person.name] = {}
            pop_persons[person.name]['id'] = person.id
            pop_persons[person.name]['name'] = person.name
            pop_persons[person.name]['following'] = person.num_following

            count += 1
            if count == 8:
                break
        return pop_persons

    @staticmethod
    def get_new_persons():
        new_persons = {}
        count = 0
        days_ago = datetime.datetime.now() - datetime.timedelta(days=7)
        persons = Person.objects.filter(created_date__gt = days_ago).annotate(
                num_following=Count('following')).order_by('-num_following')

        for person in persons:
            new_persons[person.name] = {}
            new_persons[person.name]['id'] = person.id
            new_persons[person.name]['name'] = person.name
            new_persons[person.name]['following'] = person.num_following

            count += 1
            if count == 8:
                break
        return new_persons


    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(',')
        for tag in tag_list:
            obj, created = Tag.objects.get_or_create(tag=tag.lower())
            self.tags.add(obj)

    def create_jobs(self, jobs):
        jobs = jobs.strip()
        job_list = jobs.split(',')
        for job in job_list:
            obj, created = Job.objects.get_or_create(name=job.lower())
            self.jobs.add(obj)

    def get_tags(self):
        return Tag.objects.filter(person=self)

    def get_tag3(self):
        return Tag.objects.filter(person=self)[:3]

    @property
    def total_likes(self):
        return self.user_like.count()

    @property
    def total_following(self):
        return self.following.count()   

    def get_parent(self):
        return [relation.other for relation in Relationship.objects.
            select_related("other").filter(person=self, relationship='parent')]
        # persons = Person.objects.filter(relationships__person=self, relationships__relationship='parent')
        # return persons

    def get_father(self):
        try:
            return [relation.other for relation in Relationship.objects.
                        select_related("other").filter(person=self, relationship='parent', ctype='아버지')][0]
        except Exception:
            return None

    def get_mother(self):
        try:
            return [relation.other for relation in Relationship.objects.
                        select_related("other").filter(person=self, relationship='parent', ctype='어머니')][0]
        except Exception:
            return None

    def get_spouse(self):
        return [relation.other for relation in Relationship.objects.
            select_related("other").filter(person=self, relationship='spouse')]

    def get_children(self):
        return [relation.person for relation in Relationship.objects.select_related("person").
                filter(other=self, relationship='parent').order_by('-person__sex', 'person__birth_year')]

    def get_sibling(self):
        try:
            father = self.get_father()
        except Exception as e:
            return None
        if father:
            return [relation.person for relation in Relationship.objects.select_related("person").
                filter(other=father, relationship='parent').order_by('-person__sex', 'person__birth_year')]
        else:
            return None

    def make_relationship(self, other, relationship, ctype, user):
        Relationship.objects.get_or_create(person=self, other=other, 
                relationship=relationship, ctype=ctype, created_user=user)

    # Get Nickname
    def get_nicknames(self):
        return PersonNick.objects.filter(person=self).annotate(
                num_userlike=Count('user_like')).order_by('-num_userlike')[:4]

    def get_total_nick(self):
        return PersonNick.objects.filter(person=self).annotate(
                num_userlike=Count('user_like')).count()

    def get_events(self):
        return PersonEvent.objects.filter(person=self).all()


def isNumber(s):
    try:
        float(s)
        return True
    except ValueError:
        return False


from openpyxl import load_workbook
import pandas as pd
def read_person_data():

    User = get_user_model()
    user = User.objects.get(username='happy@naver.com')

    job_array = []
    wb = load_workbook('person.xlsx')
    ws = wb['Sheet']
    df = pd.DataFrame(ws.values)

    for index, row in df.iterrows():
        if index == 0:
            continue
        print(row)
        name = row[0]
        nick = row[1]
        birth = row[2]
        sex = row[3]
        jobs = row[4]
        tags = row[5]
        status = row[6]
        event = row[7]
        news = row[8]
        father = row[9]
        mother = row[10]
        spouse = row[11]
        url = row[12]
        picture = row[13]

        if isNumber(name):
            person = Person.objects.get(id=name)
        else:
            person, created = Person.objects.get_or_create(name=name, nick_name=nick, url=url,
                    birth_year=birth, sex=sex, status=status)
            print(person)
            # 사진 입력
            if picture:
                person.picture = picture
                person.save()

            person.create_tags(name)

            # Job 입력
            if jobs:
                person.create_jobs(jobs)

        if tags:
            person.create_tags(tags)

        # 뉴스와 이벤트 가져오기
        if event:
            event = get_object_or_404(Event, id=event)
            # PersonEvent 등록
            obj, created = PersonEvent.objects.get_or_create(person=person, 
                    event=event, created_user=user)
            if created:
                print('Event {} 와 사람 {} 이 생성되었습니다.'.format(event.name, person.name))
            else:
                print('{} 은 기존 사람입니다.'.format(person.name))

            if news:
                news = news.strip()
                new_list = news.split(',')
                for new in new_list:
                    if new:
                        news = get_object_or_404(News, id=new)
                        Evidence.objects.get_or_create(personevent=obj, news=news, created_user=user)

        if father:
            fathers = Person.objects.filter(name=father)
            if len(fathers) == 1:
                person.make_relationship(fathers[0], 'parent', '아버지', user)
            else:
                print("{} 가 동명이인입니다. 다시 입력하시기 바랍니다.".format(father))

        if mother:
            mothers = Person.objects.filter(name=mother)
            if len(mothers) == 1:
                person.make_relationship(mothers[0], 'parent', '어머니', user)
            else:
                print("{} 가 동명이인입니다. 다시 입력하시기 바랍니다.".format(mother))

        if spouse:
            spouses = Person.objects.filter(name=spouse)
            if len(spouses) == 1:
                if person.sex == 'M':
                    person.make_relationship(spouses[0], 'spouse', '아내', user)
                    spouses[0].make_relationship(person, 'spouse', '남편', user)
                else:
                    person.make_relationship(spouses[0], 'spouse', '남편', user)
                    spouses[0].make_relationship(person, 'spouse', '아내', user)
            else:
                print("{} 가 동명이인입니다. 다시 입력하시기 바랍니다.".format(mother))

class Relationship(models.Model):
    person = models.ForeignKey(Person, related_name='relationships')
    other = models.ForeignKey(Person, related_name='relationothers')
    relationship = models.CharField(max_length=10, 
        choices=(('spouse', 'spouse'),('parent', 'parent'),))
    ctype = models.CharField(max_length=10, 
        choices=(('아내', '아내'),('남편', '남편'),('아버지', '아버지'),('어머니', '어머니'),('아들', '아들'),('딸', '딸'),))

mySite/records/forms.py
# records/forms.py

from PIL import Image
from django import forms
from django.forms import Textarea

# Create your forms here.
from mySite.master.models import Job
from .models import Person, Event, Evidence, Tag

class PersonForm(forms.ModelForm):
    jobs = forms.ModelMultipleChoiceField(queryset=Job.objects.all(), 
            widget=forms.CheckboxSelectMultiple)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple)
    x = forms.FloatField(widget=forms.HiddenInput(),required=False)
    y = forms.FloatField(widget=forms.HiddenInput(),required=False)
    width = forms.FloatField(widget=forms.HiddenInput(),required=False)
    height = forms.FloatField(widget=forms.HiddenInput(),required=False)
    picture = forms.FileField(required=False)

    class Meta:
        model = Person
        fields = ['name', 'nick_name', 'birth_year', 'jobs', 'picture', 'url', 'x', 'y', 'width', 'height', ]
        widgets = {
            'picture': forms.FileInput(attrs={
                'accept': 'image/*'  # this is not an actual validation! don't rely on that!
            })
        }

    # def __init__(self):
    #     super(PersonForm, self).__init__(*args, **kwargs)
    #     self.fields['tags'].initial=(tag.id for tag in Tag.objects.filter())

    def save(self):
        person = super(PersonForm, self).save()

        if not person.picture:
            return person 

        x = self.cleaned_data.get('x', 0)
        if not x:
            return person

        y = self.cleaned_data.get('y')
        width = self.cleaned_data.get('width')
        height = self.cleaned_data.get('height')

        image = Image.open(person.picture)
        cropped_image = image.crop((x, y, width+x, height+y))
        resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
        resized_image.save(person.picture.path)

        return person


class EventForm(forms.ModelForm):
    person = forms.IntegerField(widget=forms.HiddenInput())
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Tag을 입력해 주세요.'}),
                            help_text='입력할 때 ,을 이용해 구분해 주시기 바랍니다.')
    class Meta:
        model = Event
        fields = ['name', 'content', 'category', 'person']
        widgets = {
            'content': Textarea(attrs={'rows': 3}),
        }

class EvidenceForm(forms.Form):
    url = forms.URLField()


class PersonEvidenceForm(forms.ModelForm):
    personevent = forms.IntegerField(widget=forms.HiddenInput())
    news = forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = Evidence
        fields = ['personevent', 'news']

mySite/records/templates/records/include/add_person1.html
{% extends 'base.html' %}
{% load static %}

{% block main_subtree %}
    <li>
        기록 
    </li>
    <li class="active">
        <strong>사람 + 사건 + URL </strong>
    </li>
{% endblock main_subtree %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            {# FORM TITLE #}
            <div class="ibox-title">
                <h5> 사람 정보 추가 <small> 반드시 이름과 사진을 등록하여 차후 중복 등록이 없도록 합시다.</small></h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                </div>
            </div>
            {# FORM CONTENT #}
            <div class="ibox-content">
                {# FORM START #}

                <form method="POST" enctype='multipart/form-data' class="form-horizontal" id='addPersonForm'>
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-10"><input type="text" name='name' class="form-control"></div>
                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nick Name</label>
                        <div class="col-sm-10"><input type="text" name='nick_name' class="form-control">
                        <span class="help-block m-b-none">해당 인물을 잘 표현하는 별명을 입력해 주시기 바랍니다.</span></div>
                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Birth Year</label>
                        <div class="col-sm-10"><input type="text" name='birth_year' class="form-control"></div>
                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">JOB</label>
                        <div class="col-sm-10">
                            <span class="help-block m-b-none"> 직업이 해당 사항을 모두 선택하시면 됩니다.</span>
                            {% for job in jobs %}
                                <label class="checkbox-inline"> <input type="checkbox" value="{{job.id}}" name='jobs' id='id_jobs'> {{job.name}} </label>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Picture</label>
                        <div class="col-sm-10">
                            <input type="file" name='picture' class="form-control" id='id_picture' accept="image/*">
                            <span class="help-block m-b-none">해당 인물의 사진은 반드시 등록을 하시기 바랍니다.</span>
                        </div>
                        <input type="hidden" name="x" id="id_x" />
                        <input type="hidden" name="y" id="id_y" />
                        <input type="hidden" name="width" id="id_width" />
                        <input type="hidden" name="height" id="id_height" />
                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Tags</label>
                        <div class="col-sm-10"><input type="text" name='tags' class="form-control">
                        <span class="help-block m-b-none">Tag를 , 로 구분하여 입력하시기 바랍니다.</span></div>
                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <div class="col-sm-6 col-sm-offset-2">
                            <button class="btn btn-white" type="cancel">Cancel</button>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
</div>

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type='button' data-dismiss='modal' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
                <img src="" id='image' style='max-width: 100%'>
            </div>
            <div class="modal-footer">
                <div class="btn-group pull-left" role='group'>
                    <button type='button' class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type='button' class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                </div>
                <button type='button' class="btn btn-default" data-dismiss='modal'>Cancel</button>
                <button type='button' class="btn btn-primary js-crop-and-upload" data-dismiss='modal'>Crop and Upload</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
<script src="{% static 'js/cropper.min.js' %}"></script>
<script>
$(function(){

// SCRIPT TO OPEN the MODAL With the Preview
    $('#id_picture').change(function() {
        if(this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#image').attr('src', e.target.result);
                $('#modalCrop').modal("show");
            }
            reader.readAsDataURL(this.files[0]);
        }
    });

    // SCRIPTS TO HANDLE THE CROPPER BOX
    var $image = $('#image');
    var cropBoxData;
    var canvasData;

    $('#modalCrop').on('shown.bs.modal', function(){
        $image.cropper({
            viewMode: 1,
            aspectRatio: 1/1,
            minCropBoxWidth: 200,
            minCropBoxHeight: 200,
            ready: function(){
                $image.cropper('setCanvasData', canvasData);
                $image.cropper('setCropBoxData', cropBoxData);
            }
        });
    }).on('hidden.bs.modal', function(){
        cropBoxData = $image.cropper('getCropBoxData');
        canvasData = $image.cropper('getCanvasData');
        $image.cropper('destory');
    });

    $(".js-zoom-in").click(function(){
        $image.cropper('zoom', 0.1);
    })
    $(".js-zoom-out").click(function(){
        $image.cropper('zoom', -0.1);
    });

    // SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER
    $('.js-crop-and-upload').click(function(){
        var cropData = $image.cropper('getData');
        $('#id_x').val(cropData['x']);
        $('#id_y').val(cropData['y']);
        $('#id_height').val(cropData['height']);
        $('#id_width').val(cropData['width']);
        // $('#personForm').submit();
    });
});
</script>
{% endblock javascript %}


{% block backup %}
 
{% endblock backup %}

mySite/records/templates/records/include/ajax_search.html
{% for item in results %}
    <label class="checkbox-inline"> 
        <input type="checkbox" value="{{item.id}}" name='jobs' id='id_checkbox_jobs' label='{{item.name}}'> {{item.name}} 
    </label>
{% endfor %}