mySite/authentication/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^profile_edit/$', views.profile_edit, name='profile_edit'),
    url(r'^checkemail/$', views.checkemail, name='checkemail'),
    url(r'^password/$', views.password, name='password'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

mySite/records/urls.py
# records/urls.py
"""records URL Configuration"""
from django.conf.urls import url
from . import views, views_reg, views_news

urlpatterns = [
    url(r'^$', views.person_list, name='person_list'),
    url(r'^ajax_person_list/', views.ajax_person_list, name='ajax_person_list'),
    url(r'^table/$', views.person_table, name='person_table'),
    url(r'^persondetail/(?P<person_id>\d+)/$', views.person_detail, name='person_detail'),
    url(r'^personrelationship/(?P<person_id>\d+)/$', views.person_relationship, name='person_relationship'),
    url(r'^event_list/$', views.event_list, name='event_list'),
    url(r'^personfamily/(?P<person_id>\d+)/$', views.person_family, name='person_family'),
    url(r'^event_detail/(?P<event_id>\d+)/$', views.event_detail, name='event_detail'),

    url(r'^check_person/$', views_reg.check_person, name='check_person'),
    url(r'^add_person/$', views_reg.add_person, name='add_person'),
    url(r'^edit_person/(?P<person_id>\d+)/$', views_reg.edit_person, name='edit_person'),

    url(r'^check_event/(?P<person_id>\d+)/$', views_reg.check_event, name='check_event'),
    url(r'^add_event/(?P<person_id>\d+)/$', views_reg.add_event, name='add_event'),
    url(r'^person_event_matching/(?P<person_id>\d+)/$', views_reg.person_event_matching, name='person_event_matching'),

    url(r'^check_evidence/(?P<personevent_id>\d+)/$', views_reg.check_evidence, name='check_evidence'),
    url(r'^add_evidence/$', views_reg.add_evidence, name='add_evidence'),
# 9월 21일 추가함
    url(r'^evidence_add_person/(?P<news_id>\d+)/(?P<event_id>\d+)/$', views_reg.evidence_add_person, name='evidence_add_person'),

# 10/28 
    url(r'^add_event_news/(?P<event_id>\d+)/$', views_news.add_event_news, name='add_event_news'),

    url(r'^ajax_person_like/(?P<person_id>\d+)/$', views.ajax_person_like, name='ajax_person_like'),
    url(r'^ajax_person_following/(?P<person_id>\d+)/$', views.ajax_person_following, name='ajax_person_following'),

    url(r'^ajax_event_like/(?P<event_id>\d+)/$', views.ajax_event_like, name='ajax_event_like'),
    url(r'^ajax_event_following/(?P<event_id>\d+)/$', views.ajax_event_following, name='ajax_event_following'),

    url(r'^tag/(?P<tag_name>\w+)/(?P<type>\w+)/$', views.tag, name='tag'),
    url(r'^top_search/$', views.top_search, name='top_search'),

    url(r'^register_relation/(?P<person_id>\d+)/$', views.register_relation, name='register_relation'),
    url(r'^search_persons/$', views.search_persons, name='search_persons'),

    url(r'^aboutUS/$', views.aboutUS, name='aboutUS'),

]

mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as login_views
from django.conf.urls.static import static
from django.shortcuts import redirect

from mySite.authentication import views as signup_views

urlpatterns = [
    url('^$', lambda r: redirect('/records/'), name='home'),
    url(r'^xmlyoon/', admin.site.urls),
    url(r'^master/', include('mySite.master.urls', namespace='master')),
    url(r'^records/', include('mySite.records.urls', namespace='records')),
    url(r'^authentication/', include('mySite.authentication.urls', namespace='authentication')),
    url(r'^mistake/', include('mySite.mistake.urls', namespace='mistake')),
    url(r'^comments/', include('mySite.comments.urls', namespace='comments')),
    url(r'^activity/', include('mySite.activity.urls', namespace='activity')),
    url(r'^nickname/', include('mySite.nickname.urls', namespace='nickname')),
    url(r'^calendars/', include('mySite.calendars.urls', namespace='calendars')),

    url(r'^accounts/', include('allauth.urls')),
    # url(r'^evidence/', include('evidence.urls', namespace='evidence')),

    url(r'^signup/$', signup_views.signup, name='signup'),
    url(r'^login', login_views.login, {'template_name': 'authentication/login.html'},
        name='login'),
    url(r'^logout', signup_views.logout, name='logout'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mySite/authentication/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

# Create your models here.
from mySite.activity.models import Notification


class Profile(models.Model):
    """docstring for Profile"""
    """ 설명 """
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    picture = models.ImageField(upload_to='user_profile/%Y/%m/', 
                    verbose_name='', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # 성적 (등록 글, 커멘트 등에 점수를 부여함)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def notify_person_liked(self, person):
        if self.user != person.created_user:
            Notification(notification_type=Notification.LIKED, 
                from_user=self.user, to_user=person.created_user,
                person=person).save()

    def notify_person_unliked(self, person):
        if self.user != person.created_user:
            Notification.objects.filter(notification_type=Notification.LIKED,
                from_user=self.user, to_user=person.created_user,person=person).delete()

    def notify_person_commented(self, person):
        if self.user != person.created_user:
            Notification(notification_type=Notification.COMMENTED, 
                from_user=self.user, to_user=person.created_user,
                person=person).save()

    def notify_person_following(self, person):
        if self.user != person.created_user:
            Notification(notification_type=Notification.FOLLOWING, 
                from_user=self.user, to_user=person.created_user,
                person=person).save()

    def notify_person_unfollowing(self, person):
        if self.user != person.created_user:
            Notification.objects.filter(notification_type=Notification.FOLLOWING,
                from_user=self.user, to_user=person.created_user,person=person).delete()

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=settings.AUTH_USER_MODEL)
post_save.connect(save_user_profile, sender=settings.AUTH_USER_MODEL)

mySite/authentication/forms.py
from PIL import Image
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
# from bootcamp.settings import ALLOWED_SIGNUP_DOMAINS

from .models import Profile

def SignupDomainValidator(value):
    # if '*' not in ALLOWED_SIGNUP_DOMAINS:
    #     try:
    #         domain = value[value.index("@"):]
    #         if domain not in ALLOWED_SIGNUP_DOMAINS:
    #             raise ValidationError('Invalid domain. Allowed domains on this network: {0}'.format(','.join(ALLOWED_SIGNUP_DOMAINS)))  # noqa: E501

    #     except Exception:
    #         raise ValidationError('Invalid domain. Allowed domains on this network: {0}'.format(','.join(ALLOWED_SIGNUP_DOMAINS)))  # noqa: E501
    pass

def UniqueEmailValidator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this Email already exists.')

def validate_password_strength(value):
    """Validates that a password is as least 7 characters long and has at least
    1 digit and 1 letter.
    """
    min_length = 8

    if len(value) < min_length:
        raise ValidationError(_('Password must be at least {0} characters '
                                'long.').format(min_length))
    # check for digit
    if not any(char.isdigit() for char in value):
        raise ValidationError(_('Password must contain at least 1 digit.'))

    # check for letter
    if not any(char.isalpha() for char in value):
        raise ValidationError(_('Password must contain at least 1 letter.'))


class SignUpForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.HiddenInput())  # noqa: E261
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True,
        max_length=75)
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False,
        label="Name",
        max_length=75)
    password = forms.CharField(
        help_text='비밀번호는 8자 이상, 특수문자(!@#$%^&*)포함, 숫자가 포함되어야 함.',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm your password",
        required=True)

    class Meta:
        model = User
        exclude = ['last_login', 'date_joined']
        fields = ['username', 'email', 'first_name', 'password', 'confirm_password', ]

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].validators.append(UniqueEmailValidator)
        self.fields['email'].validators.append(SignupDomainValidator)
        self.fields['password'].validators.append(validate_password_strength)

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and password != confirm_password:
            self._errors['password'] = self.error_class(
                ['비밀번호가 일치하지 않습니다.'])
        return self.cleaned_data


class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Old password",
        required=True)

    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New password",
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm new password",
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        id = self.cleaned_data.get('id')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                'Old password don\'t match'])
        if new_password and new_password != confirm_password:
            self._errors['new_password'] = self.error_class([
                'Passwords don\'t match'])
        return self.cleaned_data

class ProfileForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    # existed = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Profile
        fields = ['picture', 'x', 'y', 'width', 'height', ]
        widgets = {
            'picture': forms.FileInput(attrs={
                'accept': 'image/*'  # this is not an actual validation! don't rely on that!
            })
        }

    def save(self):
        profile = super(ProfileForm, self).save()

        if not profile.picture:
            return profile 

        x = self.cleaned_data.get('x', 0)
        if not x:
            return profile
            
        y = self.cleaned_data.get('y')
        width = self.cleaned_data.get('width')
        height = self.cleaned_data.get('height')
        image = Image.open(profile.picture)
        cropped_image = image.crop((x, y, width+x, height+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(profile.picture.path)

        return profile

mySite/authentication/templates/authentication/active_email.html
{% autoescape off %}
안녕하세요. {{ user.username }} 님,

Please click on the link to confirm your registration,
등록을 마무리 하기 위해서 아래 링크를 눌러 주시기 바랍니다.

http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}
{% endautoescape %}

mySite/authentication/templates/authentication/add_picture.html
{% extends 'base.html' %}
{% load i18n static %}

{% block header-index %}
    <h2>역사를 잊은 민족에게 미래는 없다.</h2>
    <ol class="breadcrumb">
        <li>
            <a href="index.html">Home</a>
        </li>
        <li>
            기록 
        </li>
        <li class="active">
            <strong>Perosnal > Profile > 개인 정보 </strong>
        </li>
    </ol>
{% endblock header-index %}


{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            {# FORM TITLE #}
            <div class="ibox-title">
                <h5> Profile 변경 <small> 모든 곳에서 Profile 사진이 사용되니 꼭 등록을 해 주세요.</small></h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                </div>
            </div>
            {# FORM CONTENT #}
            <div class="ibox-content">
                {# FORM START #}
                <h3 style="margin-top: 0">{% trans 'Profile Picture' %}  </h3>
                <img src="{% if user.profile.picture %} {{ user.profile.picture.url }} {% else %} {% static 'images/nouser.png' %}{% endif %}" 
                    style="border-radius: 5px; margin-bottom: 1em;" width="150" id='image_existed'>

                <p>사진을 변경하시려면 파일을 선택해 주시기 바랍니다.</p>
                <form method="POST" enctype='multipart/form-data' class="form-horizontal" id="formUpload">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-group">
                        <div class="col-sm-4">
                            
                        </div>
                    </div>
                </form>
           
            </div>
        </div>
    </div>
</div>

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type='button' data-dismiss='modal' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
                <img src="" id='image' style='max-width: 100%'>
            </div>
            <div class="modal-footer">
                <div class="btn-group pull-left" role='group'>
                    <button type='button' class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type='button' class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                </div>
                <button type='button' class="btn btn-default" data-dismiss='modal'>Cancel</button>
                <button type='button' class="btn btn-primary js-crop-and-upload" data-dismiss='modal'>Crop and Upload</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block javascript %}
<link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
<script src="{% static 'js/cropper.min.js' %}"></script>
<script>
    $(function(){
        // SCRIPT TO OPEN the MODAL With the Preview

        $('#id_picture').change(function() {
            if(this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#image').attr('src', e.target.result);
                    $('#modalCrop').modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

        // SCRIPTS TO HANDLE THE CROPPER BOX
        var $image = $('#image');
        var cropBoxData;
        var canvasData;

        $('#modalCrop').on('shown.bs.modal', function(){
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1/1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                ready: function(){
                    $image.cropper('setCanvasData', canvasData);
                    $image.cropper('setCropBoxData', cropBoxData);
                }
            });
        }).on('hidden.bs.modal', function(){
            cropBoxData = $image.cropper('getCropBoxData');
            canvasData = $image.cropper('getCanvasData');
            $image.cropper('destory');
        });

        $(".js-zoom-in").click(function(){
            $image.cropper('zoom', 0.1);
        })
        $(".js-zoom-out").click(function(){
            $image.cropper('zoom', -0.1);
        });

        // SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER
        $('.js-crop-and-upload').click(function(){
            var cropData = $image.cropper('getData');
            $('#id_x').val(cropData['x']);
            $('#id_y').val(cropData['y']);
            $('#id_height').val(cropData['height']);
            $('#id_width').val(cropData['width']);
            $("#formUpload").submit();
        });

    });
    </script>
{% endblock javascript %}

mySite/authentication/templates/authentication/login.html
{% extends 'login_base.html' %}

{% load staticfiles i18n %}

{% block content %}

<style>
.wrapper{
    width: 600px;
    height: 400px;
    position: fixed;
    margin-left: -300px;
    margin-top: -200px;
    top: 50%;
    left: 50%;
}
</style>
<div class="wrapper">
    <div class="row">
        <div>
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>로그인 <small> 사용자 로그인 </small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2 class="m-t-none m-b">로그인</h2>

                            <form method="post" action="{% url 'login' %}" role="form">
                                {% csrf_token %}
                                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                                  <label>Email</label> 
                                  <input type="email" id='username' name="username" placeholder="Enter email" class="form-control">
                                  {% for error in form.username.errors %}
                                      <label class="control-label">{{ error }}</label>
                                  {% endfor %}
                                </div>

                                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                                  <label>Password</label> 
                                  <input type="password" id='password' name="password" placeholder="Enter email" class="form-control">
                                  {% for error in form.password.errors %}
                                      <label class="control-label">{{ error }}</label>
                                  {% endfor %}
                                </div>
                                <div>
                                  <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Log in</strong></button>
                                </div>
                            </form>
                        </div>

                        <div class="col-sm-6"><h3>계정이 없는 경우?</h3>
                            <a href="{% url 'signup' %}"> 
                              <p>새로운 계정을 만드시기 바랍니다.</p>
                              <p class="text-center">
                                  <i class="fa fa-sign-in big-icon"></i>
                              </p>
                            </a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block javascript %}
  <script>
    $(function(){
      $('.btn-primary').click(function(){
        var username = $('#id_email').val();
        console.log(username);
        $('#id_username').val(username);
      });
    });
  </script>
{% endblock javascript %}

mySite/authentication/templates/authentication/password.html
{% extends 'login_base.html' %}
{% load bootstrap3 %}
{% load staticfiles i18n %}

{% block content %}
<style>
.wrapper{
    width: 500px;
    height: 300px;
    position: fixed;
    margin-left: -250px;
    margin-top: -150px;
    top: 50%;
    left: 50%;
}
</style>
<div class="wrapper">
    <div class="row">
        <div>
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h4>사용자 등록</h4>
                </div>
                <div class="ibox-content">
                    <h2 class="logo">I Remember Your Past</h2>
                    <div class="signup">
                        <form action="" method="post" role="form" id='password'>
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button type="submit" class="btn btn-primary">
                                {% trans 'Change Password' %}
                            </button>
                            <a href="{% url 'home' %}" class="btn btn-primary">
                                {% trans '홈으로' %}
                            </a>
                        </form>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mySite/authentication/templates/authentication/person_profile.html
{% extends 'base.html' %}
{% load i18n static %}

{% block header-index %}
    <h2>역사를 잊은 민족에게 미래는 없다.</h2>
    <ol class="breadcrumb">
        <li>
            <a href="index.html">Home</a>
        </li>
        <li>
            기록 
        </li>
        <li class="active">
            <strong>Perosnal > Profile > 개인 정보 </strong>
        </li>
    </ol>
{% endblock header-index %}


{% block content %}
<div class="row">
    <div class="col-lg-4">
        <div class="ibox float-e-margins">
            {# FORM TITLE #}
            <div class="ibox-title">
                <h5> Profile 변경 <small> 모든 곳에서 Profile 사진이 사용되니 꼭 등록을 해 주세요.</small></h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                </div>
            </div>
            {# FORM CONTENT #}
            <div class="ibox-content">
                {# FORM START #}
                <h3 style="margin-top: 0">{% trans 'Profile Picture' %}  </h3>
                <img src="{% if user.profile.picture %} {{ user.profile.picture.url }} {% else %} {% static 'images/nouser.png' %}{% endif %}" 
                    style="border-radius: 5px; margin-bottom: 1em;" width="150" id='image_existed'>

                <p>사진을 변경하시려면 파일을 선택해 주시기 바랍니다.</p>
                <form method="POST" enctype='multipart/form-data' class="form-horizontal" id="formUpload">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-group">
                        <div class="col-sm-4">
                            
                        </div>
                    </div>
                </form>
           
            </div>
        </div>
    </div>

    {# Summary #}
    <div class="col-lg-8">
        <div class="ibox float-e-margins">
            {# FORM TITLE #}
            <div class="ibox-title">
                <h5> 획득한 점수 <small> 각 세부 항목마다 점수가 다르니 참고하시기 바랍니다. </small></h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                </div>
            </div>
            {# FORM CONTENT #}
            <div class="ibox-content">
                
           
            </div>
        </div>
    </div>
</div>

<div class="row">
    {# Content #}
    <div class="infinite-container">
    {% for person in person_list %}
        <div class="col-md-6 infinite-item">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <a href="{% url 'records:person_detail' person.id %}">
                        <strong>{{ person.name }}</strong>
                    </a>
                </div>

                <div class="ibox-content">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <a href="{% url 'records:person_detail' person.id %}">
                            <img alt="image" class="img-circle m-t-xs img-responsive" width='200px' src="{% if person.picture %} {{ person.picture.url }} {% else %} {% static 'images/nouser.png' %}{% endif %}"></a>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <p><i class="fa fa-map-marker"></i> {{ person.nick_name }} </p>
                        <p> Birth Year : {{ person.birth_year }}</p>
                        <p> Jobs :
                        {{person.jobs.all|join:", "}}
                        </p>
                        <!-- <p> Tags :
                        {{person.tags.all|join:", "}}
                        </p> -->
                    </div>
                    <div class="col-sm-4">
                        <p><i class="fa fa-share"></i> Following : {{ person.total_following }} </p>
                        <p><i class="fa fa-flag"></i> 좋아하는 사람 : {{ person.total_likes }}</p>
                        <p><i class="fa fa-flag"></i> 획득 점 : {{ person.total_likes }}</p>
                    </div>
                </div>
            </div>
        </div> {# class="col-md-6" #}

    {% endfor %}

    </div> {# class="infinite-container" #}
</div>

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type='button' data-dismiss='modal' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
                <img src="" id='image' style='max-width: 100%'>
            </div>
            <div class="modal-footer">
                <div class="btn-group pull-left" role='group'>
                    <button type='button' class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type='button' class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                </div>
                <button type='button' class="btn btn-default" data-dismiss='modal'>Cancel</button>
                <button type='button' class="btn btn-primary js-crop-and-upload" data-dismiss='modal'>Crop and Upload</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block right_side %}
    {% include 'right_side.html' with type='P' %}
{% endblock right_side %}


{% block javascript %}
<link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
<script src="{% static 'js/cropper.min.js' %}"></script>
<script>
    $(function(){
        // SCRIPT TO OPEN the MODAL With the Preview

        $('#id_picture').change(function() {
            if(this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#image').attr('src', e.target.result);
                    $('#modalCrop').modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

        // SCRIPTS TO HANDLE THE CROPPER BOX
        var $image = $('#image');
        var cropBoxData;
        var canvasData;

        $('#modalCrop').on('shown.bs.modal', function(){
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1/1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                ready: function(){
                    $image.cropper('setCanvasData', canvasData);
                    $image.cropper('setCropBoxData', cropBoxData);
                }
            });
        }).on('hidden.bs.modal', function(){
            cropBoxData = $image.cropper('getCropBoxData');
            canvasData = $image.cropper('getCanvasData');
            $image.cropper('destory');
        });

        $(".js-zoom-in").click(function(){
            $image.cropper('zoom', 0.1);
        })
        $(".js-zoom-out").click(function(){
            $image.cropper('zoom', -0.1);
        });

        // SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER
        $('.js-crop-and-upload').click(function(){
            var cropData = $image.cropper('getData');
            $('#id_x').val(cropData['x']);
            $('#id_y').val(cropData['y']);
            $('#id_height').val(cropData['height']);
            $('#id_width').val(cropData['width']);
            $("#formUpload").submit();
        });

    });
    </script>
{% endblock javascript %}